---
- hosts: eop
  become: True
  gather_facts: True
  roles:
    - eop


- hosts: jumpbox
  become: True
  gather_facts: True
  roles:
    - jumpbox    

- hosts: db
  become: True
  gather_facts: True
  roles:
    - mysql 