---
- hosts: all
  become: True
  gather_facts: True
  tasks:
    - name: Create user
      user:
        name: contrast_ssh_user
        group: wheel
        append: yes

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Copy Public SSH Key
      authorized_key:
        user: contrast_ssh_user
        state: present
        key: "{{ lookup('file', '{{ contrast_public_ssh_key }}' ) }}"


- hosts: eop
  become: True
  gather_facts: True
  roles:
    - eop


- hosts: jumpbox
  become: True
  gather_facts: True
  roles:
    - jumpbox    

- hosts: db
  become: True
  gather_facts: True
  roles:
    - mysql 