# - name: Copy Parent MySQL settings file
#   template: src={{ item.src}} dest={{ item.dest }} owner=root group=root mode=0644
#   become: yes
#   with_items:
#     - src: "etc/mysql/my.cnf"
#       dest: "/etc/mysql/my.cnf"
#     - src: "etc/mysql/conf.d/my.cnf"
#       dest: "/etc/mysql/conf.d/my.cnf"
#   notify:
#     - restart mysql-server
