---
- name: Install deps
  yum: name={{ item }} update_cache=yes state=present
  with_items:
    - mysql
    - libaio
    - libselinux-python

- name: Download from S3
  get_url: url=h{{ contrast_installer_s3 }}  dest=/opt/contrast-installer-{{ eop_version }}.sh mode=0655 backup=yes
  when: contrast_installer_s3 is defined and contrast_installer_s3 != False

- name: Copy to host
  copy: src={{ contrast_installer_local }}  dest=/opt/contrast-installer-{{ eop_version }}.sh mode=0655 backup=yes
  when: contrast_installer_local is defined

- name: Copy license file
  copy: src={{ contrast_license }} dest=/opt/contrast.lic backup=yes
  when: contrast_license is defined

- name: Copy varsfile
  copy: src=vars.txt dest=/opt/vars.txt

- name: Run the installer
  command: sudo sh /opt/contrast-installer-{{ eop_version }}.sh -q -varfile /opt/vars.txt
  when: run_install
