---
# tasks file for eop
- name: Assert that both only apache_reverse or nginx_reverse are true
  assert:
    that:
      - not (apache_reverse and nginx_reverse)
    msg: "Both apache_reverse and nginx_reverse cannot be True"

- include: eop_installer.yml
  when: eop_version is defined and run_installation is True

- include: generate_ssl_certs.yml
  when: do_ssl

- include: setup_apache_reverse_proxy.yml
  when: apache_reverse == True

- include: setup_nginx_reverse_proxy.yml
  when: nginx_reverse == True

- include: eop_webgoat-standalone.yml
  when: webgoat == True
