---
# tasks file for eop
- name: Assert that both only apache_reverse or nginx_reverse are true
  assert:
    that:
      - not (apache_reverse and nginx_reverse)
    msg: "Both apache_reverse and nginx_reverse cannot be True"

- include: eop_installer.yml
  when: eop_version is defined

- include: generate_ssl_certs.yml
  when: do_ssl

- include: setup_apache_reverse_proxy.yml
  when: apache_reverse == True

- include: setup_nginx_reverse_proxy.yml
  when: nginx_reverse == True

# - include: eop_rhel.yml
#   when: ansible_os_family == "RedHat" and eop_version is defined
#
# - include: eop_webgoat-standalone.yml
#   when: ansible_hostname == "eop-webgoat-standalone"
#
# - include: eop_webgoat-tomcat.yml
#   when: ansible_hostname == "eop-webgoat-tomcat"
