- name: Install nginx
  apt: name={{ item }} update_cache=yes state=present cache_valid_time=600
  with_items:
    - nginx

- name: Copy nginx SSL Server Template
  template: src=contrast-nginx-demo.j2 dest=/etc/nginx/sites-available/contrast-nginx-demo
  when: ansible_os_family == "Debian"
  notify: restart nginx

- name: Enable contrast-nginx-demo server
  file:
    src: /etc/nginx/sites-available/contrast-nginx-demo
    dest: /etc/nginx/sites-enabled/contrast-nginx-demo
    state: link
