---
- hosts: ts
  become: True
  gather_facts: True
  roles:
    - ansible-role-teamserver 

- hosts: ts
  serial: 1
  become: True
  gather_facts: True
  tasks:
  - name: Restart
    command: service contrast-server restart
  tags: rolling-restart